server:
  forward-headers-strategy: native
  address: 0.0.0.0
  port: 18084
  servlet:
    context-path: /api/v1/image
  ssl:
    enabled: false

spring:
  application:
    name: image-service

  web:
    resources:
      add-mappings: true

  config:
    import: 'configserver:'

  # Spring Cloud
  cloud:
    # Eureka
    client:
      hostname: image-service
    # Config
    config:
      uri: ${CONFIG_SERVER_URI}
      username: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}
      name: spring
      profile: dev
      label: main
    # Bus
    bus:
      enabled: true

  # RabbitMQ: Spring Cloud Bus 활용을 위한 설정
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# Eureka 통신
eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DEFAULT_EUREKA_URL}

minio:
  url: ${MINIO_API_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
